### ISSUE TITLE
Validar token armazenado localmente ao entrar na home page

### ISSUE THREAD

**Issue by lucas-engen** [fga-eps-mds/2021.1-Oraculo#106]
Descrição:
O frontend permite que o usuário navegue pelas demais telas mesmo que o token armazenado localmente seja inválido

Como reproduzir:
- Faça login
- Feche a janela do navegador
- Aguarde o token expirar (1h)
- Volte para a tela de login e manipule a url (apague o /login e digite /admin-page)
- Ao pressionar "enter" você será redirecionado para a tela de admin

**Comment by VictorRodriguesS0** [comment]
Issue resolvida nas issues #205 #204 #197
