### ISSUE TITLE
Alterar parametros de resposta no endpoint de editar usuário

### ISSUE THREAD

**Issue by VictorRodriguesS0** [fga-eps-mds/2021.1-Oraculo#165]
## Descrição da issue

O endpoint precisa ser alterado para realizar a edição de usuário.

## Nessa issue deve ser feito

- [x] Os campos de respota devem conter todos os atributos de usuário
- [x] Mudar endpoint para "/user/edit"

**Comment by lucas-engen** [comment]
Issue duplicada (já existe a #165)
