### ISSUE TITLE
US04: Criar um processo

### ISSUE THREAD

**Issue by ericoBandeira** [fga-eps-mds/2021.1-Oraculo#34]
## História:
Eu, como Usuário, desejo visualizar e adicionar processo , a fim de ter os metadados do processo salvos no banco de dados

## Nessa issue deve ser feito:

- [x] - Conseguir ter um processo no banco de dados, com as informações básicas do processo;
- [x] - fazer endpoint para capturar no front (get e post);

## Critérios de aceitação:

- [x] - Status 200 quando chamado com o id do processo.

**Comment by Maxlobo** [comment]
Adicionar os seguintes campos como tabelas para os processos.

 - Nº DE REGISTRO AUTOMÁTICO;
 - DATA AUTOMÁTICA;
 - ORGAO DE ORIGEM;
 - LOCALIDADE;
 - DOCUMENTO ENTRADA / NÚMERO / DATA;
 - DESCRIÇÃO DO DOCUMENTO;
 - Nº DO SEI;
 - "RECEBIDO VIA (FÍSICA; E-MAIL ;  SEI)";
 - DOCUMENTOS DE RESPOSTA / NÚMERO / DATA;
 - DADOS DO CONTATO PARA ENVIO DE RESPOSTA;
