### ISSUE TITLE
US07: Atribuir Tag's a processos

### ISSUE THREAD

**Issue by ericoBandeira** [fga-eps-mds/2021.1-Oraculo#37]
## História:
Eu, como Usuário, desejo poder marcar processos a vontade para facilitar buscas e identificações visuais de características de processos, a fim de ter mais informações sobre o andamento do processo de maneira visual.

## Nessa issue deve ser feito:

- [ ] - Adicionar uma tag a um processo no front-end
- [ ] - chamar um metodo para salvar a tag em banco de dados

## Critérios de aceitação:

- [ ] - ver a tag nova no status do backend (status 200, com a data mostrando a nova tag)
- [ ] - ver a tag com a cor certa na página de "Visualizar processo"

**Comment by VictorRodriguesS0** [comment]
@ericoBandeira Dá um help no style e CSS
