### ISSUE TITLE
Colocar as aplicações disponíveis em um ambiente de homologação com link

### ISSUE THREAD

**Issue by VictorRodriguesS0** [fga-eps-mds/2021.1-Oraculo#87]
## Descrição da issue

Gerar um ambiente de homologação online para testes de usabilidade e demosntração da aplicação.

## Nessa issue deve ser feito

- [x] Front-end
- [x] Backend - Usuários
- [x] Backend - Tags
- [x] Backend - Processos

**Comment by VictorRodriguesS0** [comment]
Link para o FrontEnd: oraculo-frontend.herokuapp.com/

**Comment by VictorRodriguesS0** [comment]
Link para o Backend de Usuários: [https://oraculo-profile.herokuapp.com/](https://oraculo-profile.herokuapp.com/)

**Comment by lucas-engen** [comment]
Todas as aplicações estão disponíveis no ambiente de homologação. O deploy é feito automaticamente após commit na branch "devel"
