### ISSUE TITLE
Token para identificação do usuário

### ISSUE THREAD

**Issue by jpaulohe4rt** [fga-eps-mds/2021.1-Oraculo#95]
## Descrição da issue
Retornar um token ao invés de um ID em usuário

[Sugestão]: <> (Uma descrição, seguindo o template do repositório, que deve incluir uma descrição completa da issue e criterios para a aceitação)

## Nessa issue deve ser feito

- [ ] Retornar um token para indentificação de casa  usuário

**Comment by lucas-engen** [comment]
O que seria essa issue mesmo? @jpaulohe4rt
